---
default:
  image: registry.prod.nub/ito/debian_packaging_images/python3:latest

variables:
  DEBIAN_DISTRIBUTION: "buster" 
  OSPOD_URL: "https://ospod.core.prod.nub/api/upload" 
  OSPOD_USER: "jenkins" 
  OSPOD_PWD: "soo4vuWi" 

stages:
  - stage1

build:
  stage: stage1
  script:
    - python3 setup.py --command-packages=stdeb.command bdist_deb
    - curl -k -g -u "$OSPOD_USER:$OSPOD_PWD" -F distribution=$DEBIAN_DISTRIBUTION -F "files[]=@$(find deb_dist -name "*.deb")" $OSPOD_URL
    - apt-get update && apt-get install -y $(find . -name "*.deb")
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}" 
    paths:
      - "**/*.deb" 
